/*
 * Problem 2
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 *       1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 */

let val_n0 = 1,
    val_n1 = 2,
    val_n2,
    sum = 0;

// Ne garder que les nombres plus petit que 4 million
while (val_n1 < 4000000) {
    // Check si le nombre est pair
    if (val_n1 % 2 == 0) {
        sum += val_n1;
    }

    // Calcule de nombre de Fibonacci suivant
    val_n2 = val_n1 + val_n0;
    val_n0 = val_n1;
    val_n1 = val_n2;
}

console.log(sum);
